name:                rofl

# Metadata used when publishing your package
synopsis:            trying to learn a new language
# category:            Web

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: 
    - src
    - ../exercises

executables:
  rofl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rofl
    - timeit
