#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(n):
	nth, cur = 1,1
	for i in range(n-1):
		nth, cur = cur, nth + cur
	return nth

if __name__ == '__main__':
	sum, n = 0,1
	while True:
		fib = fibonacci(n)
		if fib >= 4000000:
			break
		else:
			if not fib%2:
				sum += fib
			n+=1
	print(sum)
	
	